name: eproject_currensee
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:  
  sdk: ^3.6.1

#-----------------  PACKAGES  --------------------#
dependencies:
  flutter:
    sdk: flutter
  
  # Utility packages
  http: ^1.3.0
  logger: ^2.5.0
  intl: 
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  connectivity_plus: ^6.1.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.3  
  smooth_page_indicator: ^1.2.0+3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management 
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1


  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  charts_flutter_new: ^0.12.0
  fl_chart: ^0.70.2
  flutter_local_notifications: ^18.0.1
  awesome_notifications: ^0.7.4+1

#-----------------  PACKAGES END  --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
      
  flutter_lints: ^5.0.0
      
flutter:
  uses-material-design: true
        
#-----------------  LOCAL ASSETS --------------------#
  assets:
    - assets/logos/
    - assets/images/banners/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/content/
    - assets/images/reviews/
    
#-----------------  LOCAL FONTS --------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
